name: Audit

on:
  schedule:
    - cron: "0 0 * * 1"
  push:
    paths:
      - config/*.conf
      - scripts/check-package-resolution.sh
  pull_request:
    paths:
      - config/*.conf
      - scripts/check-package-resolution.sh

permissions:
  contents: read

jobs:
  package-resolution:
    name: Package Resolution
    runs-on: logaldeveloper-archlinux-ci
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Refresh pacman databases
        run: pacman -Sy --noconfirm --disable-sandbox

      - name: Check package resolution in pacman
        run: bash ./scripts/check-package-resolution.sh
