name: CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  linting:
    name: Linting
    runs-on: logaldeveloper-archlinux
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Check linting with ShellCheck
        run: git ls-files -z '*.sh' | xargs -0 -r shellcheck --external-sources
